version: '3.8'
services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    command: npm start
    ports:
      - '8081:3000'
    volumes:
      - './api:/usr/app'

  web:
    container_name: web
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - './nginx/html:/usr/share/nginx/html'